# Generated by Django 4.0.3 on 2022-03-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_todos_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('albumId', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('thumbnailUrl', models.URLField()),
            ],
        ),
    ]
