# Generated by Django 4.0.3 on 2022-03-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_company_bs_alter_company_catchphrase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.OneToOneField(default=int, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geo',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
