# Generated by Django 4.0.3 on 2022-03-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_todos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
